name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      - name: Install Ruby and Bundler
        run: |
          brew install ruby
          gem install bundler

      - name: Install CocoaPods and xcodeproj
        run: |
          gem install cocoapods --version '>= 1.16'
          gem install xcodeproj --version '>= 1.24'
          sudo gem install ffi
          pod --version  # Confirm the installed CocoaPods version

      - name: Clean CocoaPods Cache
        run: |
          pod cache clean --all

      - name: Remove Gemfile.lock (if exists)
        run: |
          rm -f ios/Gemfile.lock  # Delete Gemfile.lock if it exists in ios folder

      - name: Install Ruby dependencies (CocoaPods and Fastlane)
        run: |
          cd ios
          bundle install  # Ensure all gems in Gemfile are installed

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install  # Use bundler to ensure correct version of CocoaPods

      - name: Run Fastlane Build
        run: |
          cd ios
          bundle exec fastlane ios beta  # Use bundler to run Fastlane
