name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Ensure Ruby 2.7 is installed
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      - name: Install Bundler
        run: |
          gem install bundler -v 2.2.22  # Compatible with Ruby 2.7.x

      - name: Install CocoaPods and xcodeproj
        run: |
          gem install cocoapods --version '>= 1.16'
          gem install xcodeproj --version '>= 1.24'
          sudo gem install ffi
          pod --version  # Confirm the installed CocoaPods version

      # Only cd ios once at the beginning and then proceed with the tasks
      - name: Install Ruby dependencies (CocoaPods and Fastlane)
        run: |
          cd ios
          bundle install  # Ensure all gems in Gemfile are installed

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install  # Use bundler to ensure correct version of CocoaPods

      - name: Run Fastlane Build
        run: |
          cd ios
          bundle exec fastlane ios beta  # Use bundler to run Fastlane
