name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment with version 18
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      # Install Ruby and Bundler (for managing Ruby dependencies)
      - name: Install Ruby and Bundler
        run: |
          brew install ruby
          gem install bundler -v 2.6.5  # Install the required Bundler version

      # Install dependencies from Gemfile (including CocoaPods and Fastlane)
      - name: Install Ruby dependencies from Gemfile
        run: |
          cd ios
          bundle install  # Install dependencies using Bundler (including cocoapods)

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install  # Use Bundler to run pod install

      # Run Fastlane Build (using Bundler to ensure correct version)
      - name: Run Fastlane Build
        run: |
          cd ios
          bundle exec fastlane ios beta  # Use bundler to run Fastlane
