name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.1.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'  # Ensure Ruby 3.1.0 or higher is installed

      - name: Install CocoaPods, Bundler, and xcodeproj
        run: |
          gem install bundler
          gem install cocoapods --version '>=1.16'
          gem install xcodeproj --version '>=1.24'
          gem install fastlane
          sudo gem install ffi

      - name: Clean CocoaPods Cache
        run: |
          pod cache clean --all

      - name: Install Ruby dependencies
        run: |
          cd ios
          bundle install  # Ensure all gems in Gemfile are installed

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install  # Use bundler to ensure correct version of CocoaPods

      - name: Run Fastlane Build
        run: |
          bundle exec fastlane ios beta  # Use bundler to run Fastlane
