name: Build and Deploy iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Ruby environment with the desired Ruby version
      - name: Set up Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Set your desired Ruby version

      # Install dependencies (bundler and fastlane)
      - name: Install dependencies using Bundler
        run: |
          gem install bundler
          bundle install

      # Set up match with Git URL for certificate/provisioning profile storage
      - name: Set up Fastlane Match
        run: |
          export MATCH_GIT_URL="git@github.com:developersomesingh95/DirectWines.git"  # Replace with your Git URL
          bundle exec fastlane match development --type development --git_url $MATCH_GIT_URL

      # Build and deploy your app (customize this based on your Fastlane setup)
      - name: Build and Deploy
        run: |
          bundle exec fastlane beta  # Replace with your Fastlane lane (e.g., beta, release, etc.)
