name: Build and Deploy iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set Xcode version (adjust to a version that works for your project)
      - name: Set Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app  # Set this to the correct version
          xcode-select -p  # Ensure Xcode is set correctly

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

      # Mark build directory as created by build system
      - name: Mark build directory as created by build system
        run: |
          xattr -w com.apple.xcode.CreatedByBuildSystem true /Users/runner/work/DirectWines/DirectWines/ios/build

      # Clean the Xcode build folder
      - name: Clean Xcode build
        run: |
          cd ios
          xcodebuild clean

      # Run Fastlane
      - name: Run Fastlane
        run: fastlane ios deploy_to_app_store
        working-directory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
          MATCH_REPO_URL: '${{ secrets.MATCH_REPO_URL }}'
