name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment with version 18
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      # Install Ruby, Bundler, and Fastlane
      - name: Install Ruby, Bundler, and Fastlane
        run: |
          brew install ruby
          gem install bundler
          gem install fastlane

      # Install CocoaPods dependencies via Bundler
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle install
          bundle exec pod install

      # Set up Fastlane Match
      - name: Set up Fastlane Match
        run: |
          export MATCH_GIT_URL="git@github.com:developersomesingh95/DirectWines.git"  # Replace with your Git URL
          bundle exec fastlane match development --type development --git_url $MATCH_GIT_URL
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Run Fastlane Build (using Bundler to ensure correct version)
      - name: Run Fastlane Build
        run: |
          cd ios
          bundle exec fastlane ios beta
