name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.1.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'  # Ensure Ruby 3.1.0 or higher is installed

      - name: Install Bundler, CocoaPods, Fastlane
        run: |
          gem install bundler
          gem install cocoapods --version '>=1.16.2'
          gem install fastlane

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      - name: Install Ruby dependencies (CocoaPods and Fastlane)
        run: |
          cd ios
          bundle install  # Ensure all gems are installed

      - name: Clean CocoaPods Cache
        run: |
          pod cache clean --all

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install  # Use bundler to ensure correct version of CocoaPods

      - name: Run Fastlane Build
        run: |
          bundle exec fastlane ios beta  # Use bundler to run Fastlane
