name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Use the same Node.js version for consistency

      - name: Install Node dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      - name: Install Ruby and Bundler
        run: |
          brew install ruby
          gem install bundler
          gem install cocoapods --version '>=1.16'
          gem install xcodeproj --version '>=1.24'
          sudo gem install ffi
          pod --version  # Confirm the installed CocoaPods version

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle install  # Ensure all gems in Gemfile are installed

      - name: Clean CocoaPods Cache
        run: |
          pod cache clean --all

      - name: Run Pod Install
        run: |
          cd ios
          bundle exec pod install  # Ensure correct version of CocoaPods is used

      - name: Run Fastlane Build
        run: |
          bundle exec fastlane ios beta  # Use bundler to run Fastlane
