name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
    - uses: actions/checkout@v2

    # Step 1: Install Node Version 18
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 2: Install Ruby
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    # Step 3: Install Node Modules
    - name: Install Node Modules
      run: yarn  
      env:
        CI: true

    # Step 4: Install Bundler (Older Version for Ruby 2.7)
    - name: Install Bundler (Older Version for Ruby 2.7)
      run: gem install bundler -v 2.4.22

    # Step 5: Install Fastlane via Bundler
    - name: Install Fastlane via Bundler
      run: |
        gem install bundler -v 2.4.22
        bundle install

    # Step 6: List installed gems to verify fastlane installation
    - name: Verify Fastlane Installation
      run: gem list

    # Step 7: Install Pods
    - name: Install pods
      run: cd ios && pod install --repo-update && cd ..

    # Step 8: Ensure fastlane is installed and available
    - name: Ensure fastlane is installed
      run: |
        cd ios
        bundle exec fastlane --version  # Check that fastlane is installed and available
      working-directory: ios  # Ensure this runs inside the 'ios' directory

    # Step 9: Run Fastlane to build and ship the build
    - name: Build and upload to TestFlight
      run: |
        cd ios
        bundle exec fastlane deploy_to_app_store
      working-directory: ios  # Run Fastlane inside the 'ios' directory
      env:
        APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
        DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
        DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
        DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
        FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
        MATCH_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
        GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
        PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
        TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
        TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
        APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
        APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
        APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'