name: Build and Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment with version 18
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install Ruby 3.1.0 or higher
      - name: Install Ruby 3.1.0 or higher
        run: |
          brew install ruby@3.1
          echo 'export PATH="/opt/homebrew/opt/ruby@3.1/bin:$PATH"' >> ~/.zshrc
          source ~/.zshrc

      # Install Bundler and CocoaPods
      - name: Install Bundler and CocoaPods
        run: |
          gem install bundler -v 2.6.5
          gem install cocoapods
          pod --version

      # Install Node.js dependencies
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli

      # Clean the CocoaPods cache
      - name: Clean CocoaPods cache
        run: |
          cd ios
          rm -rf Pods
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ios/DerivedData
          pod install --repo-update

      # Install Ruby dependencies from Gemfile
      - name: Install Ruby dependencies from Gemfile
        run: |
          cd ios
          bundle install

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install

      # Run Fastlane Build with verbose logging
      - name: Run Fastlane Build with verbose logging
        run: |
          cd ios
          bundle exec fastlane ios beta --verbose
